### ISSUE TITLE
[Epic] - Features

### ISSUE THREAD

**Issue by LauraAubin** [LauraAubin/not-your-average-crayon#1]
### Draw on top of existing images
- [ ] Pen tool
- [ ] Pen -> text alignment
- [ ] Line break
- [ ] Hold `command` key to enter "editor" mode, default to "preview"

### Quick form input
- [ ] Regular form
- [ ] [Ability to click on a specific location to start typing](https://github.com/LauraAubin/not-your-average-crayon/issues/2)
   - [ ] Blank areas
   - [ ] Right aligned
   - [ ] Middle of existing text
   - Maintain internals as a form instead of a canvas in order to retain classic form experience
- [ ] Last line is not the end of the container, visually more room to grow, similar to Google Docs' nearly infinite scrolling
